# Generated by Django 3.2.9 on 2022-01-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_userprofileinfo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='aboutme',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
