# Generated by Django 3.2.9 on 2022-01-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_userprofileinfo_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='aboutme',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
