# Generated by Django 3.2.9 on 2022-01-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_auto_20220102_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='about',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
