# Generated by Django 3.2.18 on 2023-04-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='market',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('facebook', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('google_location', models.CharField(default='', max_length=200)),
                ('market_manager', models.CharField(default='', max_length=200)),
                ('date', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
                ('rating', models.CharField(default='', max_length=200)),
                ('shirt', models.IntegerField(default=0)),
                ('pants', models.IntegerField(default=0)),
                ('shoes', models.IntegerField(default=0)),
                ('hat', models.IntegerField(default=0)),
                ('gloves', models.IntegerField(default=0)),
                ('scarf', models.IntegerField(default=0)),
                ('jacket', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
            ],
        ),
    ]
