# Generated by Django 3.2.18 on 2023-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
