# Generated by Django 3.2.18 on 2023-04-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_submissions_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='submissions',
            new_name='submission',
        ),
    ]
