# Generated by Django 3.2.18 on 2023-04-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_submissions_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='myEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=10)),
                ('market_id', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
