# Generated by Django 3.2.18 on 2023-05-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230509_1426'),
        ('main', '0008_auto_20230509_1727'),
    ]

    operations = [
    ]
