# Generated by Django 3.2.18 on 2023-05-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_message_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
    ]
