# Generated by Django 3.2.18 on 2023-05-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='myevent',
            name='gloves',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='myevent',
            name='hat',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='myevent',
            name='jacket',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='myevent',
            name='other',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='myevent',
            name='pants',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='myevent',
            name='scarf',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='myevent',
            name='shirt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='myevent',
            name='shoes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
